name: Django CI with python

on:
  #  pull_request:
  #    branches: [ "main" ] # master로 PR시 Actions 작동
  push:
    branches: [ "main" ] # master로 PR시 Actions 작동

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Copy .env
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # docker 시작
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_PW}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: . # base folder
          file: ./Dockerfile # Dockerfile path
          platforms: linux/amd64 # m1에서는 - linux/arm64/v8
          push: true # github 저장소 명으로 도커 imagename 설정
          tags: ojy9612/${{ github.event.repository.name }}:latest # username/imagename:tagname  tagname 생략 시 latest로 입력됨.
